name: Sync Repos to Gitee
on:
  push:
    branches:
      - main  # 触发分支，与你源仓库的主分支一致
jobs:
  clone-and-push:
    runs-on: ubuntu-latest
    steps:
      # 设置 Gitee 的 SSH 私钥
      - name: Set up SSH Key for Gitee
        uses: ssh-actions/ssh-key-action@v2
        with:
          key: ${{ secrets.GITEE_PRIVATE_KEY }}
          known_hosts: |
            gitee.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNQAAAAIbmlzdHAyNQAAABBBFSM65nuL2l7WmsnCkQ17nLmHm38G6/8B8RQ3W2z+6V0R3sD7V7yFqPw59Nk6lO0zW/5KQp6s7r42h3C07X0Rg=

      # 同步 MobileGlues-release 仓库
      - name: Sync MobileGlues-release to Gitee
        run: |
          git clone --depth 1 https://github.com/MobileGL-Dev/MobileGlues-release.git
          cd MobileGlues-release
          git remote add gitee git@gitee.com:hai_ou1/MobileGlues-release.git
          git config user.name "hai_ou1"
          git config user.email "a13854250594a@qq.com"
          git push -f gitee --all
          git push -f gitee --tags

      # 同步 FoldCraftLauncher 仓库
      - name: Sync FoldCraftLauncher to Gitee
        run: |
          git clone --depth 1 https://github.com/FCL-Team/FoldCraftLauncher.git
          cd FoldCraftLauncher
          git remote add gitee git@gitee.com:hai_ou1/FoldCraftLauncher.git
          git config user.name "hai_ou1"
          git config user.email "a13854250594a@qq.com"
          git push -f gitee --all
          git push -f gitee --tags
