name: 同步仓库到Gitee

on:
  push:
    paths-ignore:
      - '*.md'
  schedule:
    - cron: '0 0 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 配置SSH
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.GITEE_PRIVATE_KEY }}
      - name: 配置Git用户信息
        run: |
          git config --global user.email "a13854250594a@qq.com"
          git config --global user.name "hai_ou1"
      - name: 同步FoldCraftLauncher仓库
        env:
          GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
          GITEE_USER: ${{ secrets.GITEE_USER }}
        run: |
          git clone --mirror https://github.com/FCL-Team/FoldCraftLauncher.git
          cd FoldCraftLauncher
          git remote set-url --push origin git@gitee.com:hai_ou1/FoldCraftLauncher.git
          git push --mirror origin
      - name: 同步MobileGlues - release仓库
        env:
          GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
          GITEE_USER: ${{ secrets.GITEE_USER }}
        run: |
          git clone --mirror https://github.com/MobileGL-Dev/MobileGlues-release.git
          cd MobileGlues-release
          git remote set-url --push origin git@gitee.com:hai_ou1/MobileGlues-release.git
          git push --mirror origin
