name: Test Gitee Access
on: [push]

jobs:
  test-gitee-clone:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Gitee Repository
        run: |
          # 构造带令牌的 HTTPS 仓库 URL（格式：https://<token>@gitee.com/<owner>/<repo>.git）
          repo_url="https://${{ secrets.GITEE_TOKEN }}@gitee.com/your-gitee-username/your-repo-name.git"
          git clone $repo_url
          # 或使用更安全的 --config 参数（避免令牌出现在命令历史）
          # git clone https://x-access-token:${{ secrets.GITEE_TOKEN }}@gitee.com/your-gitee-username/your-repo-name.git
