name: Sync Repositories to Gitee

on:
  push:
    paths-ignore:
      - README.md
      - README_EN.md
      - README_RU.md
      - README_CHT.md
      - README_CN.md
      - README_JP.md
  schedule:
    - cron: '0 0 * * *' # 每天凌晨执行一次，可根据需求调整

jobs:
  sync-repositories:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.6
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure Git
        run: |
          git config --global user.email "a13854250594a@qq.com"
          git config --global user.name "hai_ou1"

      - name: Sync FoldCraftLauncher
        env:
          GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
          GITEE_USERNAME: ${{ secrets.GITEE_USERNAME }}
        run: |
          git clone --mirror https://github.com/FCL-Team/FoldCraftLauncher.git
          cd FoldCraftLauncher
          git remote set-url --push origin git@gitee.com:hai_ou1/FoldCraftLauncher.git
          git push --mirror origin

      - name: Sync MobileGlues-release
        env:
          GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
          GITEE_USERNAME: ${{ secrets.GITEE_USERNAME }}
        run: |
          git clone --mirror https://github.com/MobileGL-Dev/MobileGlues-release.git
          cd MobileGlues-release
          git remote set-url --push origin git@gitee.com:hai_ou1/MobileGlues-release.git
          git push --mirror origin
