name: Mirror Repositories to Gitee

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  mirror-FoldCraftLauncher:
    runs-on: ubuntu-latest
    steps:
      - name: Create .ssh directory
        run: mkdir -p ~/.ssh
      - name: Create config file
        run: echo "Host github.com\nHostname ssh.github.com\nPort 443" > ~/.ssh/config
      - name: Set config file permissions
        run: chmod 600 ~/.ssh/config
      - name: Add GitHub host key to known_hosts
        run: mkdir -p ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts && chmod 600 ~/.ssh/known_hosts
      - name: Checkout FoldCraftLauncher
        uses: actions/checkout@v3
        with:
          repository: FCL-Team/FoldCraftLauncher
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure Git for FoldCraftLauncher
        run: git config --global user.email "a13854250594a@qq.com" && git config --global user.name "hai_ou1"
      - name: Add SSH Key for FoldCraftLauncher
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.GITEE_PRIVATE_KEY }}
      - name: Clone and Overwrite to Gitee for FoldCraftLauncher
        run: echo "开始克隆仓库" && git clone --mirror git@github.com:FCL-Team/FoldCraftLauncher.git && if [ -d FoldCraftLauncher.git ]; then echo "FoldCraftLauncher.git 仓库克隆成功"; else echo "FoldCraftLauncher.git 仓库克隆失败"; fi && cd FoldCraftLauncher.git && echo "已进入克隆后的仓库目录，准备推送到 Gitee" && git push --mirror --force git@gitee.com:hai_ou1/FoldCraftLauncher.git && push_result=$? && if [ $push_result -eq 0 ]; then echo "仓库推送成功"; else echo "仓库推送失败"; fi

  mirror-MobileGlues-release:
    runs-on: ubuntu-latest
    steps:
      - name: Create .ssh directory
        run: mkdir -p ~/.ssh
      - name: Create config file
        run: echo "Host github.com\nHostname ssh.github.com\nPort 443" > ~/.ssh/config
      - name: Set config file permissions
        run: chmod 600 ~/.ssh/config
      - name: Add GitHub host key to known_hosts
        run: mkdir -p ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts && chmod 600 ~/.ssh/known_hosts
      - name: Checkout MobileGlues-release
        uses: actions/checkout@v3
        with:
          repository: MobileGL-Dev/MobileGlues-release
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
          timeout: '600s'
      - name: Configure Git for MobileGlues-release
        run: git config --global user.email "a13854250594a@qq.com" && git config --global user.name "hai_ou1"
      - name: Add SSH Key for MobileGlues-release
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.GITEE_PRIVATE_KEY }}
      - name: Clone and Overwrite to Gitee for MobileGlues-release
        run: echo "开始克隆仓库" && git clone --mirror git@github.com:MobileGL-Dev/MobileGlues-release.git && if [ -d MobileGlues-release.git ]; then echo "MobileGlues-release.git 仓库克隆成功"; else echo "MobileGlues-release.git 仓库克隆失败"; fi && cd MobileGlues-release.git && echo "已进入克隆后的仓库目录，准备推送到 Gitee" && git push --mirror --force git@gitee.com:hai_ou1/MobileGlues-release.git && push_result=$? && if [ $push_result -eq 0 ]; then echo "仓库推送成功"; else echo "仓库推送失败"; fi

  test-ssh-key:
    runs-on: ubuntu-latest
    steps:
      - name: Create .ssh directory if not exists
        run: mkdir -p ~/.ssh
      - name: Add Gitee host key to known_hosts
        run: |
          ssh-keyscan -t rsa -H gitee.com >> ~/.ssh/known_hosts
          if [ -s ~/.ssh/known_hosts ]; then
            echo "Gitee host key added successfully. Known_hosts content: $(cat ~/.ssh/known_hosts)"
          else
            echo "Failed to add Gitee host key. known_hosts file is empty or does not exist."
          fi
      - name: Test SSH Connection to Gitee
        run: |
          echo "${{ secrets.GITEE_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa_gitee
          chmod 600 ~/.ssh/id_rsa_gitee
          if [ -s ~/.ssh/id_rsa_gitee ]; then
            echo "SSH private key written successfully. Private key content: $(cat ~/.ssh/id_rsa_gitee)"
          else
            echo "Failed to write SSH private key. Private key file is empty or does not exist."
          fi
          ssh -T git@gitee.com
