name: Test Gitee Access
on: [push]

jobs:
  test-gitee-api:
    runs-on: ubuntu-latest
    steps:
      - name: Test Gitee API with Token
        run: |
          # 使用 curl 发送带认证的请求到 Gitee API（如获取用户信息）
          # 格式：https://<token>@gitee.com/api/v5/user
          # 或使用 --user 参数（更安全，避免令牌出现在命令历史）
          curl --silent --request GET \
               --url "https://gitee.com/api/v5/user" \
               --user "x-access-token:${{ secrets.GITEE_TOKEN }}" \
               --output response.json
          # 检查响应状态码是否为 200（成功）
          status_code=$(curl --write-out "%{http_code}" --silent --output /dev/null "https://gitee.com/api/v5/user" --user "x-access-token:${{ secrets.GITEE_TOKEN }}")
          if [ "$status_code" -ne 200 ]; then
            echo "Error: Gitee API access failed with status code $status_code"
            exit 1
          else
            echo "Success: Gitee API accessible (Status Code: 200)"
          fi
