name: Mirror Repositories to Gitee

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  mirror-FoldCraftLauncher:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout FoldCraftLauncher
        uses: actions/checkout@v3
        with:
          repository: FCL-Team/FoldCraftLauncher
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure Git for FoldCraftLauncher
        run: |
          git config --global user.email "a13854250594a@qq.com"
          git config --global user.name "hai_ou1"
      - name: Add SSH Key for FoldCraftLauncher
        uses: webfactory/ssh-agent@v0.5.5
        with:
          ssh-private-key: ${{ secrets.GITEE_PRIVATE_KEY }}
      - name: Clone and Overwrite to Gitee for FoldCraftLauncher
        run: |
          git clone --mirror git@github.com:FCL-Team/FoldCraftLauncher.git
          cd FoldCraftLauncher.git
          git push --mirror --force git@gitee.com:hai_ou1/FoldCraftLauncher.git

  mirror-MobileGlues-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout MobileGlues-release
        uses: actions/checkout@v3
        with:
          repository: MobileGL-Dev/MobileGlues-release
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure Git for MobileGlues-release
        run: |
          git config --global user.email "a13854250594a@qq.com"
          git config --global user.name "hai_ou1"
      - name: Add SSH Key for MobileGlues-release
        uses: webfactory/ssh-agent@v0.5.5
        with:
          ssh-private-key: ${{ secrets.GITEE_PRIVATE_KEY }}
      - name: Clone and Overwrite to Gitee for MobileGlues-release
        run: |
          git clone --mirror git@github.com:MobileGL-Dev/MobileGlues-release.git
          cd MobileGlues-release.git
          git push --mirror --force git@gitee.com:hai_ou1/MobileGlues-release.git
