name: Sync Repositories to Gitee

on:
  # 监控源仓库的所有推送事件
  push:
    paths-ignore:
      - README.md
      - README_EN.md
      - README_RU.md
      - README_CHT.md
      - README_CN.md
      - README_JP.md
  # 定期同步，每24小时执行一次
  schedule:
    - cron: '0 0 * * *'

jobs:
  sync-repositories:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout FoldCraftLauncher Repository
        uses: actions/checkout@v4
        with:
          repository: FCL - Team/FoldCraftLauncher
          path: FoldCraftLauncher
          ref: main  # 替换为需要的分支、标签等
      - name: Checkout MobileGlues - release Repository
        uses: actions/checkout@v4
        with:
          repository: MobileGL - Dev/MobileGlues - release
          path: MobileGlues - release
          ref: main  # 替换为需要的分支、标签等
      - name: Set up SSH private key
        uses: webfactory/ssh - agent@v0.5.1
        with:
          ssh - private - key: ${{ secrets.GITEE_PRIVATE_KEY }}
      - name: Push FoldCraftLauncher to Gitee
        run: |
          cd FoldCraftLauncher
          git config user.name ${{ secrets.GITEE_USER }}
          git config user.email a13854250594a@qq.com
          git remote add gitee git@gitee.com:${{ secrets.GITEE_USER }}/FoldCraftLauncher.git
          git push -f gitee main  # 替换为需要推送的分支
      - name: Push MobileGlues - release to Gitee
        run: |
          cd MobileGlues - release
          git config user.name ${{ secrets.GITEE_USER }}
          git config user.email a13854250594a@qq.com
          git remote add gitee git@gitee.com:${{ secrets.GITEE_USER }}/MobileGlues - release.git
          git push -f gitee main  # 替换为需要推送的分支
