name: Sync Repositories to Gitee

on:
  # 监控源仓库的所有推送事件
  push:
    paths-ignore:
      - README.md
      - README_EN.md
      - README_RU.md
      - README_CHT.md
      - README_CN.md
      - README_JP.md
  # 定期同步，每24小时执行一次
  schedule:
    - cron: '0 0 * * *'

jobs:
  sync-repositories:
    runs-on: ubuntu-latest

    steps:
      # 检出代码到临时目录
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置SSH私钥
      - name: Set up SSH private key
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.GITEE_PRIVATE_KEY }}

      # 同步FoldCraftLauncher仓库
      - name: Sync FoldCraftLauncher Repository
        uses: yjc1995/git-clone-repo@v1.3.1
        with:
          remote: origin
          source: https://github.com/FCL-Team/FoldCraftLauncher.git
          destination: FoldCraftLauncher
          token: ${{ secrets.GITEE_TOKEN }}
          user: ${{ secrets.GITEE_USER }}
          email: a13854250594a@qq.com
          gitee: true
          tags: true
          releases: true
          force: true
        env:
          GIT_SSH_COMMAND: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no

      # 同步MobileGlues-release仓库
      - name: Sync MobileGlues-release Repository
        uses: yjc1995/git-clone-repo@v1.3.1
        with:
          remote: origin
          source: https://github.com/MobileGL-Dev/MobileGlues-release.git
          destination: MobileGlues-release
          token: ${{ secrets.GITEE_TOKEN }}
          user: ${{ secrets.GITEE_USER }}
          email: a13854250594a@qq.com
          gitee: true
          tags: true
          releases: true
          force: true
        env:
          GIT_SSH_COMMAND: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
